services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Пароль для root из .env
      MYSQL_DATABASE: ${MYSQL_DB}            # Имя базы данных из .env
                # Имя пользователя из .env
         # Пароль пользователя из .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  telegram-bot:
    build:
      context: ./my_tg_bot/Deadline_code/Back
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: always
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
